name: Run webscraper

on:
  workflow_dispatch:
    inputs:
      scraper_param:
        description: "Parameter for webscraper.py"
        required: true
        default: "default_value"

jobs:
  run-webscraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
      # pip install -r dexscraper/requirements.txt
    - name: Install SeleniumBase
      run: |
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are flake8 issues
        flake8 . --count --show-source --statistics --exclude=temp
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run webscraper.py
      run: |
        python dexscraper/a.py
      # python dexscraper/webscraper.py "${{ github.event.inputs.scraper_param }}"
